### ISSUE TITLE
iOS & "Optimize PNG images" setting

### ISSUE THREAD

**Issue by TomSoderling** [brminnick/ImproveXamarinBuildTimes#4]
This isn't an issue, per-se, but it's not mentioned in this document and wanted to throw this out there to see if anyone has some insight on this. 

I'm find that a lot of my build time (~4.5 minutes) is spent running pngcrush on 573 images in our solution. So for iOS simulator builds, turning off "Optimize PNG images" has a dramatic effect, brining a 5+ minute build down to 45 seconds.

**Comment by TheCodeTraveler** [comment]
Thanks Tom! I added it in 👍

**Comment by saamerm** [comment]
@brminnick Sorry I don't get it, you added it into what?

**Comment by TheCodeTraveler** [comment]
Unchecked the "Optimize PNG Images" box in the iOS Build Settings
![picture1](https://user-images.githubusercontent.com/13558917/43540649-2b46f668-957d-11e8-8239-7615de1b15b7.png)
